@startchen

entity FirstResponder {
  Name
  ID <<key>>
  Position
  Location
  OnCallStatus
}

entity OnlineNurse {
  Name
  ID <<key>>
  Position
  ShiftSchedule
  Available
}

entity HealthcareProfessional {

  Specialization
  ShiftSchedule
  OnCallStatus
  Username
  Password
}

entity Patient {
  Name
  PHN <<key>>
  HealthCareCardNumber
  Location
  Gender
  Birthdate
  Occupation
HealthRecords
queuePosition
}

entity SystemAdmin {
  Name
  ID <<key>>
  Position
Schedule
}

entity Symptom <<weak>> {
  Symptom_Info
}


entity Hospital {
  Name
  ID <<key>>
  Location
  EstimatedWaitTime
  PhoneNumber
  Capacity
}



entity TriageReport <<weak>> {
  ReportID <<key>>
  ReportContent
  DateCreated
}

relationship exhibitsSymptoms {
}

relationship provideTechSupport {
supportTicket
}


relationship createsTriageReport {
}

relationship treatsPatient {
}

relationship triagesPatient {
recommendation
}

relationship assistsPatient {
}

relationship employedAt {
}

Patient -1- exhibitsSymptoms
exhibitsSymptoms -N- Symptom

OnlineNurse -1- createsTriageReport
createsTriageReport -N- TriageReport
Patient -1- createsTriageReport

HealthcareProfessional -N- treatsPatient
treatsPatient -N- Patient

OnlineNurse -1- triagesPatient
triagesPatient -N- Patient

FirstResponder -N- assistsPatient
assistsPatient -N- Patient

HealthcareProfessional -N- employedAt
OnlineNurse -N- employedAt
FirstResponder -N- employedAt
SystemAdmin -N- employedAt
employedAt -1- Hospital

SystemAdmin -1- provideTechSupport
provideTechSupport -N- Patient
provideTechSupport -N- OnlineNurse
provideTechSupport -N- HealthcareProfessional
provideTechSupport -N- FirstResponder
@endchen